version: "3.8"

services:
  user_postgres:
    container_name: transaction_postgres
    image: "postgres:latest"
    environment:
      POSTGRES_DB: transaction
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - transaction_postgres_data:/var/lib/postgresql/data

volumes:
  transaction_postgres_data: