server:
  port: 8080

spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: user
#    password: password
  profiles:
    active: dev
#logging:
#  level:
#    root: warn